In [1]:
print("Hello Python")
print()
import os
import sys
path = sys.executable
print(path)

Hello Python

c:\program files\python38\python.exe


### tensorflow study
#### 2020.06.09

In [4]:
import tensorflow as tf
tf.__version__

'2.2.0'

In [ ]:
import torch

## Tensor의 개념
### Numpy라는 라이브러리를 사용하여 간단하게 이해하자..
### Scalar, Vector, Matrix, Tensor가 있음
### 선 -> 면 -> 입체.. 고차원적인 데이터를 딥러닝에서 많이 사용

In [22]:
import numpy as np

### 0차원
- numpy array는 1 또는 5, 10와 같이 숫자 데이터를 array화 해줄 수 있음


In [10]:
arr = np.array(8)

In [12]:
arr

array(8)

In [14]:
arr.shape

()

- -> Scalar로 들어갔을 때는 shape가 아무것도 없는 것으로 나온다, shape라는게 모양을 나타내는 것?인데 모양이 없기 때문(뒤에서 설명), ndim은 차원의 개수

In [15]:
arr.ndim

0

### 1차원
- 

In [17]:
arr = np.array([5])
arr

array([5])

In [18]:
arr.shape

(1,)

- 숫자가 하나만 들어간다고 해도 리스트를 씌우게 되면 차원이 하나가 생긴다. 하지만 리스트에 여러 숫자를 추가한다고 해도 차원이 늘어나는 것은 아니며, 하나의 리스트 안에 있는 것은 1차원이다. 사이즈가 달라도.

In [19]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [21]:
arr1.shape

(3,)

In [22]:
#(3) -> (3,) 

### 2차원
- 대괄화를 추가적으로 씌우면 차원이 추가적으로 하나 생김

In [23]:
arr = np.array([[1, 2, 3]]) #value가 3개인 리스트가 하나 있다는 shape이 된다, 리스트안에 리스트를 만들어줬기 때문에.
arr.shape

(1, 3)

- 위의 shape을 다시 보면 차원이 2개가 있고, 각 차원마다 각각 3개의 값(value)가 들어있다고 생각하면 됨

In [32]:
arr = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]]) # 하나의 대괄호에 1차원[1, 2, 3]이 3개가 있는 것 (3,3) -> 3개가 3개 모였다.
arr.shape

2

- 참고로 0차원 숫자에 대문자에 대괄호를 2번 씌우면 두개의 차원이 됨

In [35]:
arr = np.array([[10]])
arr.shape

(1, 1)

In [33]:
arr.ndim

2

### 다 차원

In [41]:
arr = np.array([[[[1, 2 ,3], [1, 2 ,3], [1, 2 ,3]], [[1, 2 ,3], [1, 2 ,3], [1, 2 ,3]]], [[[1, 2 ,3], [1, 2 ,3], [1, 2 ,3]], [[1, 2 ,3], [1, 2 ,3], [1, 2 ,3]]]])
arr

array([[[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]])

In [43]:
arr.shape

(2, 2, 3, 3)

In [45]:
arr = np.array([[[1], [2] ,[3]], [[1], [2] ,[3]], [[1], [2] ,[3]]])
arr

array([[[1],
        [2],
        [3]],

       [[1],
        [2],
        [3]],

       [[1],
        [2],
        [3]]])

In [46]:
arr.shape

(3, 3, 1)

In [3]:
!pip install --upgrade tensorflow-gpu

Defaulting to user installation because normal site-packages is not writeable


Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


Defaulting to user installation because normal site-packages is not writeable

Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: tensorflow-gpu 2.2.0 requires tensorflow-gpu-estimator<2.3.0,>=2.2.0, which is not installed.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.



  Attempting uninstall: tensorflow-gpu
    Found existing installation: tensorflow-gpu 2.2.0
    Uninstalling tensorflow-gpu-2.2.0:
      Successfully uninstalled tensorflow-gpu-2.2.0


## Tensorflow Hello world!

In [15]:
import tensorflow as tf

with tf.compat.v1.Session() as sess:
  h = tf.constant("Hello")
  w = tf.constant("World!")
  hw = h + w
  ans = sess.run(hw)
  print(ans)

b'HelloWorld!'


In [16]:
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(4.0) #also tf.float32 implicitly
node3 = tf.add(node1, node2)

In [18]:
print("node1:", node1, "node2:", node2)
print("node3:", node3)

node1: tf.Tensor(3.0, shape=(), dtype=float32) node2: tf.Tensor(4.0, shape=(), dtype=float32)
node3: tf.Tensor(7.0, shape=(), dtype=float32)


# Numpy 기초1
### zeros & ones
- 0으로 채워진 numpy array를 만들 수 있음

In [3]:
import numpy as np
zeros = np.zeros([3, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
zeros = np.zeros(1)
zeros

array([0.])

In [5]:
ones = np.ones([10])
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
ones = np.ones([10, 5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [10]:
ones * 6

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

### 1차원 array 만들기, arange를 사용해서

In [10]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [11]:
arr = np.arange(4, 9)
arr

array([4, 5, 6, 7, 8])

In [12]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### 

In [4]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Index

In [14]:
nums = [1, 2, 3, 4, 5]

In [15]:
nums[2:]

[3, 4, 5]

In [17]:
nums = [1, 2, 3, 4, [1, 2, 3]]
nums

[1, 2, 3, 4, [1, 2, 3]]

In [18]:
nums[4]

[1, 2, 3]

In [20]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
arr[1][2]

5

In [22]:
arr[0]

array([0, 1, 2])

In [23]:
arr[1]

array([3, 4, 5])

In [24]:
arr[2]

array([6, 7, 8])

### Slicing

In [5]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [25]:
arr[0:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr[1:, 0]

array([3, 6])

In [7]:
arr[1:, 1]

array([4, 7])

In [28]:
arr[1:, 2]

array([5, 8])

In [9]:
arr[0:, 1]

array([1, 4, 7])

In [29]:
arr[1:, 1:]

array([[4, 5],
       [7, 8]])

### Boolean Indexing

In [30]:
data = np.random.randn(3, 3)
data

array([[-1.88348432,  0.71496601,  1.40838169],
       [-0.06921767, -0.16455411, -0.57644101],
       [-0.11310097,  0.88224354,  1.46010581]])

#### 위 결과에서 음수를 양수를 구분하여 출력해보고 싶다

In [31]:
data <= 0 # 각 value 마다 boolean을 반환 (각 value의 값이 0보다 작거나 같을 때 True -> 음수는 모두 True)

array([[ True, False, False],
       [ True,  True,  True],
       [ True, False, False]])

In [32]:
data[data <= 0] # boolean 결과를 리스트로 묶으면 아래와 같이 해당하는 값만 출력

array([-1.88348432, -0.06921767, -0.16455411, -0.57644101, -0.11310097])

In [34]:
data[data <= 0] = 1 # true에는 1값을 넣어줌, 조건에 해당하는 값에 1을 대입하여 출력
data

array([[1.        , 0.71496601, 1.40838169],
       [1.        , 1.        , 1.        ],
       [1.        , 0.88224354, 1.46010581]])

### Broadcast
- tensorflow나 python으로 계산하면 broadcast의 개념 이해가 필요
- broadcast는 연산하려는 서로 다른 2개의 행렬의 shape가 같지 않고, 한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일때 이를 여러번 복사하여 연산을 함

In [10]:
import numpy as np

In [37]:
arr = np.arange(9).reshape(3, 3) # 1차원 array를 2차원으로 만들기 -> reshape. 위에서도 나옴
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
arr + 3 # 각 value에 3씩 더하여 출력

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
arr * 3 # 각 value에 3씩 곱하여 출력

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [41]:
arr + np.array([1, 2, 3]) # 1, 2, 3씩 더하여 출력

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

### Math Function

- numpy로 수학적인 연산해보기

In [42]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [43]:
arr * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [44]:
arr + arr  ## arr 끼리 더할 수도 있다.

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [45]:
np.add(arr, 1) # arr 더하기를 이처럼 표현할 수도 있다.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
np.multiply(arr, 3) # 곱하기는 multiply를 사용

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

## 랜덤한 numpy array를 2개 만들어 보기

- randint : 0부터 2전까지의 숫자를 랜덤하게 만들고, 그 사이즈를 27개로 만들어 달라. 그 다음 마지막으로 reshape를 3 by 3으로 해달라.

In [12]:
arr = np.random.randint(2, size=27).reshape(3, 3, 3)    
arr_2 = np.random.randint(2, size=9).reshape(3, 3)

In [49]:
arr

array([[[0, 1, 1],
        [1, 1, 1],
        [1, 1, 0]],

       [[1, 1, 1],
        [1, 0, 1],
        [1, 1, 1]],

       [[0, 0, 1],
        [1, 1, 0],
        [0, 0, 0]]])

In [50]:
arr.shape

(3, 3, 3)

In [51]:
arr # arr확인

array([[[0, 1, 1],
        [1, 1, 1],
        [1, 1, 0]],

       [[1, 1, 1],
        [1, 0, 1],
        [1, 1, 1]],

       [[0, 0, 1],
        [1, 1, 0],
        [0, 0, 0]]])

In [52]:
arr_2 #arr_2 확인

array([[1, 1, 1],
       [0, 1, 0],
       [0, 0, 1]])

In [53]:
arr.shape, arr_2.shape # shape도 다른 것 확인

((3, 3, 3), (3, 3))

In [54]:
arr + arr_2 # 2개의 arr 더하기

array([[[1, 2, 2],
        [1, 2, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [1, 1, 1],
        [1, 1, 2]],

       [[1, 1, 2],
        [1, 2, 0],
        [0, 0, 1]]])

In [13]:
arr * arr_2 # 2개의 arr 곱하기

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 1, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 1, 0]]])

In [55]:
np.sum(arr) # arr 모든 값 더하기

18

In [14]:
np.sum(arr + arr_2) # 2개의 arr 모든 값 더하기

22

In [15]:
np.max(arr) # arr에서 제일 큰 값

1

In [16]:
np.max(arr + arr_2) # 각 arr에서 제일 큰 값을 더하기

2

In [17]:
np.min(arr + arr_2) # 각 arr에서 제일 작은 값을 더하기, 가장 작은 값이 둘다 0이니까 0.

0

In [18]:
np.max(arr + arr_2, 0) # 0차원에서 제일 큰 값들 반환

array([[1, 0, 1],
       [1, 1, 1],
       [1, 2, 2]])

In [19]:
np.max(arr + arr_2, -1) # 1차원에서 제일 큰 값들 반환

array([[1, 1, 2],
       [1, 1, 2],
       [1, 1, 2]])

## 아래 다시 정리

In [22]:
#먼저 arr+arr_2
arr + arr_2

array([[[0, 0, 1],
        [1, 0, 1],
        [0, 2, 1]],

       [[1, 0, 1],
        [1, 1, 1],
        [0, 2, 2]],

       [[0, 0, 1],
        [1, 0, 1],
        [1, 2, 1]]])

In [20]:
np.sum(arr + arr_2, 0) # 0+1+0=1, 0+0+0=0, 1+1+1=3

array([[1, 0, 3],
       [3, 1, 3],
       [1, 6, 4]])

In [23]:
np.sum(arr + arr_2, -1) # 0+0+1=1, 1+0+1=2, 0+2+1=3

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 4]])

In [25]:
np.sum(arr + arr_2, axis=-1) # axis를 주어서 차원을 입력하는 것도 가능

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 4]])

In [26]:
np.mean(arr)

0.37037037037037035

### 새로운 array 만들기

In [32]:
arr1 = np.array([1,6,3,7,3,2,9,0,2])
arr1

array([1, 6, 3, 7, 3, 2, 9, 0, 2])

In [30]:
np.argmax(arr1) # 6번째 있는 인덱스가 제일 크다. 즉, 9가 제일 크다

6

In [33]:
np.argmin(arr1) # 7번째 있는 인덱스인 0이 제일 작다.

7

In [34]:
np.unique

<function numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)>

## 또 새로운 array 만들기

In [35]:
arr2 = np.array([3,5,6,6,6,3,3,1])

In [36]:
arr2

array([3, 5, 6, 6, 6, 3, 3, 1])

In [37]:
np.unique(arr2) # 가장 unique한 값들만 가져온다.

array([1, 3, 5, 6])